version: "3.2"

services:
     database:
         build:
             context: ./database
         ports:
             - "5432:5432"
         image: database
         environment:
             - POSTGRES_USER=admin
             - POSTGRES_PASSWORD=admin
             - POSTGRES_DB=dhis2
         volumes:
              - type: volume
                source: dbdata
                target: /var/lib/postgresql/data
         restart: unless-stopped

     webcontainer:
         build:
             context: ./webcontainer
         ports:
             - "8080:8080"
         image: webcontainer
         depends_on:
             - "database"
         volumes:
           - type: bind
             source: /opt/dhis/data/war
             target: /usr/local/tomcat/webapps
           - type: bind
             source: /opt/dhis/data/logs
             target: /usr/local/tomcat/logs
         restart: unless-stopped

     webserver:
         build:
             context: ./webserver
         image: webserver
         restart: always
         ports:
             - "80:80"
             - "443:443"
         depends_on:
             - "webcontainer"
         volumes:
             - type: bind
               source: /etc/letsencrypt
               target: /etc/letsencrypt
             - type: bind
               source: /var/www/letsencrypt
               target: /var/www/letsencrypt
volumes:
  dbdata:
